### ISSUE TITLE
Amelioration fonctionnalité menu, menu pause

### ISSUE THREAD

**Issue by Jidev84** [DeGaRoR/DeGaRoR.github.io#32]
Modifier l'onglet de "préférences" dans le jeu
![Sans titretyjil](https://user-images.githubusercontent.com/92604857/137548562-69415089-0624-43df-a015-38ca7cdf052e.jpg)
s

**Comment by DeGaRoR** [comment]
Nouveau menu à tester + feedback stp

**Comment by Jidev84** [comment]
Fonctionne nickel
