### ISSUE TITLE
Indicateurs de population

### ISSUE THREAD

**Issue by DeGaRoR** [DeGaRoR/DeGaRoR.github.io#53]

**Comment by DeGaRoR** [comment]
J'ai une première version, optimisée pour mobile. Il faudra rendre cela plus grand sur écran PC

**Comment by DeGaRoR** [comment]
![image](https://user-images.githubusercontent.com/25803280/139618412-c3719d12-1a64-407f-b1ba-fa628b0fc894.png)

**Comment by Jidev84** [comment]
Sympa ! J'aime bien le principe

**Comment by Jidev84** [comment]
Roh même pas moyen de faire sortir la barre de l'écran. T'as bien fait ça 
![Screenshot_20211101_135228_com android chrome](https://user-images.githubusercontent.com/92604857/139675026-37c39823-c237-4462-afc2-54012bd4a6da.jpg)
