### ISSUE TITLE
Change the title

### ISSUE THREAD

**Issue by DeGaRoR** [DeGaRoR/DeGaRoR.github.io#55]
Il est si bôôô. Je pourrais aussi améliorer le menu principal dans l'esprit de la bannière

**Comment by Jidev84** [comment]
Mieux?

![Titrexbc1](https://user-images.githubusercontent.com/92604857/139557680-b2886798-dc84-411f-870a-9fb68d25fea4.jpg)

**Comment by DeGaRoR** [comment]
Ouais j'aime bien! Tu me l'optimises au niveau résolution, png fond transparent? J'aime bien le côté un peu retro 80s.

**Comment by Jidev84** [comment]
Meilleure résolution, png et même deux choix (un avec plus de bubulles :p)
![Titrexbc3](https://user-images.githubusercontent.com/92604857/139558613-559c41d4-d10f-477a-80c9-c0b18f84adf2.png)
![Titrexbc2](https://user-images.githubusercontent.com/92604857/139558612-de8c3039-6124-4c01-97f9-5bc073768e2a.png)

**Comment by DeGaRoR** [comment]
Super rendu sur plein écran. Sur mobile, je pense qu'il vaudrait mieux sur 2 lignes, bien centré. Tu peux me faire ça stp? Looking gooooood ;-)

**Comment by DeGaRoR** [comment]
Je l'ai fait, mais si tu veux faire une version mieux, n'hésite pas

**Comment by Jidev84** [comment]
Montre  :)
Je ne visualise pas bien ce que tu veux dire par deux lignes

**Comment by Jidev84** [comment]
Encore un petit ajustement et ça sera bon 
![Sans titre](https://user-images.githubusercontent.com/92604857/139561687-f4bfca6e-074c-4a6d-bf5f-24592d2ca05d.jpg)

Ca donne bien en tout cas !

**Comment by DeGaRoR** [comment]
Passe en mode mobile tu verras

**Comment by Jidev84** [comment]
![Screenshot_20211101_001548_com android chrome](https://user-images.githubusercontent.com/92604857/139604520-b97d7893-fe3b-4cb8-a51b-c2d98a0fa586.jpg)
Ca claque
