### ISSUE TITLE
Mise à jour app

### ISSUE THREAD

**Issue by Jidev84** [DeGaRoR/DeGaRoR.github.io#68]
Voir comment implémenter les mises à jour de l'appli une fois téléchargée sur mobile

**Comment by DeGaRoR** [comment]
J'ai compris, il faut mettre à jour le nom du service worker pour qu'il dclenche une mise à jour. Tu peux tester: ouvre ton app installée, et tu devrais avoir la dernière version avec les indicateurs de population et le tuto jusqu'au niveau 4

**Comment by Jidev84** [comment]
Ca fonctionne !

**Comment by DeGaRoR** [comment]
J'ai changé la stratégie de récupération des données, maintenant il va systématiquement chercher à avoir le tout dernier contenu s'il y a de la connectivité. Sinon c'est OK offline aussi. Désinstalle l'app, fais un gros clear du stockage, et normalement il ne devrait plus y avoir de différence entre l'app et le browser
