### ISSUE TITLE
Niveau 5 qui déconne 

### ISSUE THREAD

**Issue by Jidev84** [DeGaRoR/DeGaRoR.github.io#71]
Les IA n'attaquent pas et tentent de faire évoluer leur base alors qu'elles sont stuck niveau 1

Vidéo plus explicite sur le drive
https://drive.google.com/file/d/1k29qleggCTjQz7uDPcO9ULbIAW-CVUwz/view?usp=drivesdk

**Comment by DeGaRoR** [comment]
Devrait être réglé, à tester

**Comment by Jidev84** [comment]
Réglé
