### ISSUE TITLE
Cahier des charges musique

### ISSUE THREAD

**Issue by DeGaRoR** [DeGaRoR/DeGaRoR.github.io#72]

**Comment by DeGaRoR** [comment]
== Musique ==
menu.music
game.music

== Effets sonores ==

-- Unités --
unit.killed
unit.spawn?

-- Bases --
base.upgraded ?= base.acquired
base.destroyed

-- Indicateurs progressifs --
base.upgrading ?= base.acquiring(quand la base est partiellement conquise)
base.destroying (quand les bases sont attaquées et perdent de la vie)

-- Game --
game.won
game.lost
game.start?

**Comment by Jidev84** [comment]
Je peux te trouver ça en version libre. Il faut un format particulier? Midi? MP3?
