### ISSUE TITLE
Resizer l'écran modifie la vitesse de jeu !

### ISSUE THREAD

**Issue by Jidev84** [DeGaRoR/DeGaRoR.github.io#76]
J'ai fini par comprendre comment j'avais eu un truc chelou avec les unité super lentes. 
Le problème semble être sur pc uniquement.
Modifier la taille de l'écran de jeu par exemple en dézoomant (ctrl+molette), rend le jeu plus lent ! (production des unités, déplacements etc)
Remettre à la taille d'origine ne règle pas le problème et il faut refresh pour remettre à zéro

**Comment by DeGaRoR** [comment]
Le jeu n'est pas plus lent, le spawn est pareil. C'est juste la distance qui est plus grande, mais les icônes des unités et bases sont aussi magnifiées
