### ISSUE TITLE
Nouveau menu general

### ISSUE THREAD

**Issue by Jidev84** [DeGaRoR/DeGaRoR.github.io#77]
- Mettre un bouton de retour au site web ( soit dans le menu déroulant du jeu, soit dans le menu de sélection des niveaux)
- Un bouton avec les infos du studio, le facebook etc. ne serait pas du luxe non plus.
- Mettre les liens indispensables vers le patreon, kickstarter, moyen de nous soutenir financièrement (payez un café) 

Exemple en screenshot ici :

![Sans titre1](https://user-images.githubusercontent.com/92604857/139971515-d502025f-3eb3-4b98-aa78-e7bbeace9112.jpg)
![Sans titre2](https://user-images.githubusercontent.com/92604857/139971534-70e8d019-a8fd-48e2-8b5d-1d1969612461.jpg)

**Comment by Jidev84** [comment]
En voyant ce genre d'exemple pris au hasard, je me demande dans quelle mesure ça ne serait pas mal de faire un menu de jeu avec dedans 3 options :
- Tutoriel (et mettre les 3/4 niveaux tuto dedans, à part des autres niveaux)
- Le menu de sélection de niveaux
- Les infos du studio

Dis moi ce que tu en pense et si c'est facile ou pas à implémenter. C'est du polissage mais je pense que ça serait vraiment un plus.

**Comment by DeGaRoR** [comment]
J'aime pas trop mettre le tuto à part, je crois que c'est bien d'avoir des étoiles "gratuites".

Au niveau menu, je verrais bien:
- Un count des étoiles totales, pour faire chaud au coeur, genre 26/100
- Le bouton PLAY qui renvoie à la selection des niveaux
- Un bouton éditeur de niveaux
- Un bouton options pour
     * choisir la langue
     * Désactiver le tuto
     * Options de son
- Un call-for-action, inciter à dépenser
- Un petit bouton crédits
- Des liens direct médias sociaux, ne pas cacher derrière un menu
- Logo PugFace pour retour au studio, ptet avec un truc genre "A game by Pugface Production <logo>"

**Comment by DeGaRoR** [comment]
Fait, à tester
![image](https://user-images.githubusercontent.com/25803280/140914440-9d472cc1-58eb-4ee6-82a3-1da43a1c6193.png)
