### ISSUE TITLE
Differents objectifs de temps par niveau

### ISSUE THREAD

**Issue by DeGaRoR** [DeGaRoR/DeGaRoR.github.io#89]

**Comment by DeGaRoR** [comment]
Je pense que ce n'est plus nécessaire vu la vitesse plus élevée. Les niveaux peuvent tous se finir en dessous de 2 minutes je crois

**Comment by Jidev84** [comment]
Je pense qu'une des trois étoiles pourrait être de finir le niveau en un temps limite. 
Ce ne serait pas obligatoire pour tous les niveaux, selon ce que tu voudrait mettre d'autre comme objectif.
Ca signifie mettre un compteur de temps in game aussi !
